/** @type {import('tailwindcss').Config} */
// module.exports = {
//   content: [
//     "./src/**/*.{html,ts}",
//   ],
//   theme: {
//     extend: {},
//   },
//   plugins: [],
// }

module.exports = {
  theme: {
    extend: {
      gridTemplateColumns: {
        // 23 column grid
        '23': 'repeat(23, minmax(0, 1fr))',
      },
      screens: {
        '3xl': '1600px',
      }
    }
  },
  content: [
    "./src/**/*.{html,ts}",
  ],
  corePlugins: [
    'alignContent',
    'alignItems',
    'alignItems',
    'animation',
    'appearance',
    'aspectRatio',
    'backdropBlur',
    'backdropBrightness',
    'backdropContrast',
    'backdropFilter',
    'backdropGrayscale',
    'backdropSaturate',
    'borderColor',
    'borderStyle',
    'borderRadius',
    'borderWidth',
    'boxDecorationBreak',
    'boxSizing',
    'breakAfter',
    'breakAfter',
    'breakInside',
    'clear',
    'container',
    'columns',
    'display',
    'divideColor',
    'divideStyle',
    'divideWidth',
    'flex',
    'flexBasis',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'floats',
    'gridAutoColumns',
    'gridAutoFlow',
    'gridAutoRows',
    'gridColumn',
    'gridColumnEnd',
    'gridColumnStart',
    'gridRow',
    'gridRowEnd',
    'gridRowStart',
    'gridTemplateColumns',
    'gridTemplateRows',
    'isolation',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    'margin',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'outlineColor',
    'outlineOffset',
    'outlineStyle',
    'outlineWidth',
    'overflow',
    'padding',
    'position',
    'placeContent',
    'placeItems',
    'placeSelf',
    'ringColor',
    'ringOffsetColor',
    'ringOffsetWidth',
    'ringWidth',
    'space',
    'transitionDelay',
    'transitionDuration',
    'transitionProperty',
    'transitionTimingFunction',
//    'visibility',
    'width',

  ]
}
